### ISSUE TITLE
Building solaris 11-2 - not working so far

### ISSUE THREAD

**Issue by nicferrier** [BigAl/solaris-packer#2]
I'm doing a virtualbox build of the 11-2 packer. 

A cursory glance suggests that it's not even selecting the language properly, the:

```
27<enter>
```

doesn't result in US-English being selected.

**Comment by BigAl** [comment]
Do you have more info.  Like versions of packer,  vagrant,  VirtualBox,  what host OS?  I have built a new baseboard recently and but i suspect with with the frequence of changes of all of these there are some potential issues.  The biggest issue is a lot of this is thinking dependant and if VirtualBox is too slow,  or to  fast too boot then you will have issues.  For example if I tried to build  2 baselines at once one would often not work.

**Comment by nicferrier** [comment]
Host OS: Ubuntu.
Vagrant: 1.6.3
Packer: 0.7.5
VirtualBox: 4.3.10_Ubuntur93012

I wasn't trying to do anything clever. It didn't seem to be a speed thing. It was just not selecting what the script said. I've happily installed solaris 11.2 via the same media as a virtualbox image on this machine... it was just the script driving that didn't work.

**Comment by BigAl** [comment]
Can't replicate problem
