### ISSUE TITLE
Solaris 11.1 Vurtial Box creationg failed - virtualbox-iso: Error waiting for SSH: ssh: handshake failed

### ISSUE THREAD

**Issue by tsp0001** [BigAl/solaris-packer#3]
Hi Al,

I was pretty much using the files you supplied with minor changes. When I tried to run packer build command - it gave the error below.
It would not authenticate and get authorized keys from my GitHub repository nor if I established them on my local workstation.

$ Packer_0.7.5/packer.exe build -only=virtualbox-iso /c/HashiCorp/Vagrant/Sol11.1_proj/solaris-packer/solaris11.j son

virtualbox-iso output will be in this color.
==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: file:///C:/HashiCorp/Vagrant/Sol11.1_proj/sol-11_1-live-x86.iso
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for SSH (host port 4331)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-solaris-11 --memory 1024
    virtualbox-iso: Executing: modifyvm packer-solaris-11 --cpus 1
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 1m35s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password keyboard-interactive], no supported methods remain
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Build was halted.
==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Build was halted.
==> Builds finished but no artifacts were created.

Here is my postinstall.sh file:
# !/bin/sh
# setup the vagrant key
# you can replace this key-pair with your own generated ssh key-pair

echo "Setting the vagrant ssh pub key"
mkdir /export/home/vagrant/.ssh
chmod 700 /export/home/vagrant/.ssh
touch /export/home/vagrant/.ssh/authorized_keys
scp -pr 10.239.15.13:/export/home/sxp49/.ssh/vagrant.pub /export/home/vagrant/.ssh/authorized_keys
chmod 600 /export/home/vagrant/.ssh/authorized_keys
chown -R vagrant:staff /export/home/vagrant/.ssh
echo "Post-install done"

**Comment by BigAl** [comment]
Can't replicate problem.
